name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy files to VPS
      uses: appleboy/scp-action@master
      with:
        host: 45.93.137.103
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        source: ./
        target: /root/workspace/liftingbot

    - name: SSH into VPS and run deployment script
      uses: appleboy/ssh-action@master
      with:
        host: 45.93.137.103
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/workspace/liftingbot/lifts-logger
          source .env
          python exercise_bot.py
